"""
Aura Financial Tracker - Vulnerable Version
Challenge Catalog (Sprint 41: Sound Breathing - String Performance)

Static data for the hidden /scoreboard page. One entry per VULN-ID in
docs/vulnerability-matrix.md (86 total as of Sprint 53, including VULN-065
which is fixed and kept here only for transparency/completeness).

Each hint is a tier-1, category-level hint per this project's cybersecurity
skill's progressive-hint system: it points at the general area and technique
class, never the exact route, parameter, or payload. Finding those is the
whole point of the challenge.
"""

CHALLENGES = [
    {"vuln_id": "VULN-001", "name": "Plaintext Password Storage", "category": "Cryptographic Failures", "severity": "critical", "status": "active",
     "hint": "Check how - and where - this app actually stores your password."},
    {"vuln_id": "VULN-002", "name": "Missing Auth on Admin Panel", "category": "Broken Access Control", "severity": "critical", "status": "active",
     "hint": "Some pages assume you'll never think to just navigate somewhere you weren't given a link to."},
    {"vuln_id": "VULN-003", "name": "Weak Password Policy", "category": "Authentication Failures", "severity": "low", "status": "active",
     "hint": "Try registering with the shortest, weakest password you can think of."},
    {"vuln_id": "VULN-004", "name": "Information Disclosure (Debug)", "category": "Security Misconfiguration", "severity": "low", "status": "active",
     "hint": "Somewhere in this app is a debug view that was probably never meant to ship."},
    {"vuln_id": "VULN-005", "name": "No Input Validation", "category": "Injection", "severity": "medium", "status": "active",
     "hint": "Almost nothing you type into this app is checked before it's used."},
    {"vuln_id": "VULN-006", "name": "SQL Injection - Login", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "The login form might trust what you type a little too literally."},
    {"vuln_id": "VULN-007", "name": "SQL Injection - Registration", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Registration builds a database query the same risky way the login form does."},
    {"vuln_id": "VULN-008", "name": "IDOR - User Profiles", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Profile pages sometimes forget to check whose profile you're actually looking at."},
    {"vuln_id": "VULN-009", "name": "Stored XSS - Username", "category": "Injection", "severity": "high", "status": "active",
     "hint": "A username is just text - until the app renders it somewhere without treating it that way."},
    {"vuln_id": "VULN-010", "name": "No CSRF Protection", "category": "Broken Access Control", "severity": "medium", "status": "active",
     "hint": "A form that trusts every request from a logged-in browser, regardless of where the request actually came from, can be tricked into acting on someone else's behalf."},
    {"vuln_id": "VULN-011", "name": "No Rate Limiting", "category": "Authentication Failures", "severity": "medium", "status": "active",
     "hint": "Nothing stops you - or a script - from trying the login form as many times as you want."},
    {"vuln_id": "VULN-012", "name": "Predictable Session Tokens", "category": "Authentication Failures", "severity": "medium", "status": "active",
     "hint": "Look closely at how a session identifier is actually generated."},
    {"vuln_id": "VULN-013", "name": "Session Fixation", "category": "Authentication Failures", "severity": "medium", "status": "active",
     "hint": "A session id that exists before login might not necessarily change after login."},
    {"vuln_id": "VULN-014", "name": "Insecure Cookie Config", "category": "Cryptographic Failures", "severity": "medium", "status": "active",
     "hint": "Look at how the session cookie is configured, not just whether one exists."},
    {"vuln_id": "VULN-015", "name": "SQL Injection - Transaction Create", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Creating a transaction might build its database query the same unsafe way the login form does."},
    {"vuln_id": "VULN-016", "name": "SQL Injection - Category CRUD", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Category management touches the database in every direction - create, read, update, delete - worth checking if all of them are equally careless."},
    {"vuln_id": "VULN-017", "name": "SQL Injection - Dashboard Filters", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Filtering the transaction list might pass your filter values straight into a query."},
    {"vuln_id": "VULN-018", "name": "IDOR - Transaction Access", "category": "Broken Access Control", "severity": "critical", "status": "active",
     "hint": "Transaction endpoints don't always double-check that the record you're asking for actually belongs to you."},
    {"vuln_id": "VULN-019", "name": "IDOR - Category Management", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Category management has the same 'whose data is this really' problem as other record types in this app."},
    {"vuln_id": "VULN-020", "name": "Stored XSS - Transaction Desc", "category": "Injection", "severity": "high", "status": "active",
     "hint": "A transaction description is user-controlled text that eventually gets displayed somewhere."},
    {"vuln_id": "VULN-021", "name": "Stored XSS - Category Name", "category": "Injection", "severity": "high", "status": "active",
     "hint": "Category names, like usernames, are rendered back to you - worth checking how."},
    {"vuln_id": "VULN-022", "name": "Mass Assignment - Transactions", "category": "Insecure Design", "severity": "high", "status": "active",
     "hint": "A transaction create request accepts more fields than it probably should - including ones that decide who owns it."},
    {"vuln_id": "VULN-023", "name": "No Input Validation - Amounts", "category": "Insecure Design", "severity": "low", "status": "active",
     "hint": "Nothing stops an amount field from being negative, zero, or absurd."},
    {"vuln_id": "VULN-024", "name": "No CSRF on API", "category": "Broken Access Control", "severity": "medium", "status": "active",
     "hint": "Not every API call bothers to verify a request actually originated from this app's own pages."},
    {"vuln_id": "VULN-025", "name": "Reflected XSS - Filters", "category": "Injection", "severity": "medium", "status": "active",
     "hint": "A filter value that only lives in the URL might still end up rendered straight into the page."},
    {"vuln_id": "VULN-026", "name": "Info Disclosure - API", "category": "Security Misconfiguration", "severity": "low", "status": "active",
     "hint": "API responses sometimes include more about a record's internals than the UI ever displays."},
    {"vuln_id": "VULN-027", "name": "Race Condition - Edits", "category": "Insecure Design", "severity": "low", "status": "active",
     "hint": "Two near-simultaneous edits to the same record might not be handled as safely as you'd expect."},
    {"vuln_id": "VULN-028", "name": "SQL Injection - Account CRUD", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Account operations build queries the same way transactions and categories do - for better or worse."},
    {"vuln_id": "VULN-029", "name": "SQL Injection - Recurring Transactions", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Recurring transaction rules touch the database with the same lack of caution as one-off transactions."},
    {"vuln_id": "VULN-030", "name": "IDOR - Account Management", "category": "Broken Access Control", "severity": "critical", "status": "active",
     "hint": "Accounts can sometimes be read or changed by anyone who can guess or increment an id."},
    {"vuln_id": "VULN-031", "name": "IDOR - Recurring Transactions", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Recurring transaction rules have the same ownership-check gap as other resources in this app."},
    {"vuln_id": "VULN-032", "name": "Mass Assignment - Accounts", "category": "Insecure Design", "severity": "high", "status": "active",
     "hint": "Account creation and updates accept the same kind of extra, unchecked fields as transactions do."},
    {"vuln_id": "VULN-033", "name": "Mass Assignment - Recurring", "category": "Insecure Design", "severity": "high", "status": "active",
     "hint": "Recurring transaction rules have the same over-trusting create/update behavior as accounts and transactions."},
    {"vuln_id": "VULN-034", "name": "Business Logic - Budget Balance", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "The 'budget balance' figure is calculated from a set of accounts - think about how that set gets decided."},
    {"vuln_id": "VULN-035", "name": "Business Logic - Soft Delete Orphan", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "Deleting an account might not be as final, or as clean, as it looks."},
    {"vuln_id": "VULN-036", "name": "SQL Injection - Transfer CRUD", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Moving money between accounts involves a database write - check how carefully it's built."},
    {"vuln_id": "VULN-037", "name": "SQL Injection - Budget CRUD", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Budgets are managed with the same query-building habits as everything else in this app."},
    {"vuln_id": "VULN-038", "name": "SQL Injection - Savings Goals", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Savings goals share the same database-query pattern as budgets and transfers."},
    {"vuln_id": "VULN-039", "name": "IDOR - Transfer Management", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Transfers between accounts don't always verify which user actually owns the accounts involved."},
    {"vuln_id": "VULN-040", "name": "IDOR - Budget Management", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Budgets can sometimes be viewed or edited without proving they're yours."},
    {"vuln_id": "VULN-041", "name": "IDOR - Savings Goals", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Savings goals share the same missing ownership check as budgets and transfers."},
    {"vuln_id": "VULN-042", "name": "CSV Injection - Export", "category": "Injection", "severity": "medium", "status": "active",
     "hint": "A CSV export is meant to be opened in a spreadsheet - think about what a spreadsheet program does with certain leading characters."},
    {"vuln_id": "VULN-043", "name": "SQL Injection via CSV Import", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Importing data back in might be even less careful than exporting it out."},
    {"vuln_id": "VULN-044", "name": "No Auth on Export Endpoints", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Exporting data is convenient - maybe too convenient, if it doesn't check who's asking."},
    {"vuln_id": "VULN-045", "name": "Business Logic - Goal No Auto-Achieve", "category": "Insecure Design", "severity": "low", "status": "active",
     "hint": "A savings goal that reaches its target amount doesn't necessarily know it."},
    {"vuln_id": "VULN-046", "name": "SQL Injection - Dashboard Name", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Naming or renaming a dashboard is still user input reaching a query."},
    {"vuln_id": "VULN-047", "name": "Stored XSS - Dashboard Name", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "A dashboard's name shows up in a tab bar you'll see on every visit - worth checking how it's rendered."},
    {"vuln_id": "VULN-048", "name": "IDOR - Edit Any Dashboard", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Editing a dashboard might not actually require it to be your dashboard."},
    {"vuln_id": "VULN-049", "name": "IDOR - Delete Any Dashboard", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "If editing someone else's dashboard works, deleting it is worth trying too."},
    {"vuln_id": "VULN-050", "name": "IDOR - Add Widget to Any Dashboard", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Adding a widget to a dashboard id you found somewhere else might just work."},
    {"vuln_id": "VULN-051", "name": "IDOR - Remove Any Widget", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Removing a widget by id may not check which dashboard - or which user - it actually belongs to."},
    {"vuln_id": "VULN-052", "name": "Mass Assignment - Dashboard Create", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "Creating a dashboard accepts a field that probably shouldn't be up to the client to decide."},
    {"vuln_id": "VULN-053", "name": "No CSRF on Dashboard CRUD", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "The newer dashboard and widget endpoints might have the same missing-request-origin-check as the older API endpoints."},
    {"vuln_id": "VULN-054", "name": "SQL Injection via category_ids filter", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Filtering a report by a list of category ids might build that filter unsafely."},
    {"vuln_id": "VULN-055", "name": "SQL Injection via account_ids filter", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Filtering by a list of account ids might have the same problem as filtering by category ids."},
    {"vuln_id": "VULN-056", "name": "Stored XSS via custom widget title", "category": "Injection", "severity": "high", "status": "active",
     "hint": "A dashboard widget's custom title is more user input rendered somewhere on the page."},
    {"vuln_id": "VULN-057", "name": "SQL Injection via custom_title in UPDATE", "category": "Injection", "severity": "high", "status": "active",
     "hint": "That same custom widget title might also reach a database update unsafely."},
    {"vuln_id": "VULN-058", "name": "SQL Injection - Dashboard Queries", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Basic dashboard operations - listing, activating, seeding defaults - might all share the same query-building habit."},
    {"vuln_id": "VULN-059", "name": "SQL Injection - Widget State Queries", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Widget state changes, like position or minimized state, touch the database too - worth checking how."},
    {"vuln_id": "VULN-060", "name": "SQL Injection - Reports Data Endpoints", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "The reporting endpoints all pull data scoped to a user - check what actually scopes that query."},
    {"vuln_id": "VULN-061", "name": "IDOR - Dashboard List/Activate", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Listing or activating dashboards by id might not require they be yours."},
    {"vuln_id": "VULN-062", "name": "IDOR - Widget List & Update State", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Widget state updates might accept any widget id, not just ones on your own dashboards."},
    {"vuln_id": "VULN-063", "name": "No Authentication - Dashboard & Reports-Data APIs", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "An entire family of dashboard and reporting endpoints might not check for a session at all."},
    {"vuln_id": "VULN-064", "name": "Unvalidated Exchange Rate (No Bounds Check)", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "An exchange rate is just a number in a form - nothing stops it from being zero, negative, or wildly wrong, and that number quietly flows into everything priced in that currency."},
    {"vuln_id": "VULN-065", "name": "SQL Injection - Exchange Rate CRUD", "category": "Injection", "severity": "critical", "status": "fixed",
     "hint": "This one used to live in how exchange rates were saved - it's been patched since, so treat it as closed, not a live target."},
    {"vuln_id": "VULN-066", "name": "Stored XSS - Currency Code", "category": "Injection", "severity": "high", "status": "active",
     "hint": "A currency code is short, but it's still user-supplied text that ends up displayed somewhere."},
    {"vuln_id": "VULN-067", "name": "XXE + Unbounded Input - OFX Import", "category": "Security Misconfiguration", "severity": "critical", "status": "active",
     "hint": "A bank-statement import feature has to parse a file format that allows more than just transaction data - think about what else that format's syntax permits, and whether anything limits how big or how deep the file can be."},
    {"vuln_id": "VULN-068", "name": "SQL Injection - OFX/QIF Import", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Bank-file imports parse untrusted file content and then touch the database with it."},
    {"vuln_id": "VULN-069", "name": "IDOR - Import Destination Account", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "An import feature that lets you pick a destination account is only as safe as its check that the account is actually yours."},
    {"vuln_id": "VULN-070", "name": "IDOR - Dashboard/Widget Reorder", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Reordering dashboards might accept ids that don't belong to you at all."},
    {"vuln_id": "VULN-071", "name": "No Cross-Dashboard Validation - Widget Reorder", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "A widget-reorder request might only check that a widget id exists - not that it belongs to the dashboard you're editing."},
    {"vuln_id": "VULN-072", "name": "SQL Injection + IDOR + Verbose Errors - Analytics Endpoints", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "The analytics endpoints reveal a lot when something goes wrong with the request - including their own error messages."},
    {"vuln_id": "VULN-073", "name": "SQL Injection + IDOR - Notification Endpoints", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Notifications are scoped to a user by an id that arrives with every request - check where that id actually comes from."},
    {"vuln_id": "VULN-074", "name": "Stored XSS via Notification Content", "category": "Injection", "severity": "high", "status": "active",
     "hint": "Notification text ultimately comes from things you've already put into the app elsewhere."},
    {"vuln_id": "VULN-075", "name": "SQL Injection + IDOR - AI Advisor Endpoints", "category": "Sensitive Information Disclosure", "severity": "critical", "status": "active",
     "hint": "The AI advisor's chat history is fetched using a user id passed with the request, not necessarily derived from who's actually logged in."},
    {"vuln_id": "VULN-076", "name": "Insecure API Key Storage - Groq Key via Debug Endpoint", "category": "Sensitive Information Disclosure", "severity": "high", "status": "active",
     "hint": "Whatever that debug view discloses, it's worth checking if it got worse once this app started calling external AI services."},
    {"vuln_id": "VULN-077", "name": "Prompt Injection (Direct + Indirect) - AI Advisor", "category": "Prompt Injection", "severity": "critical", "status": "active",
     "hint": "The AI assistant reads context that includes things you've typed elsewhere in the app, like transaction descriptions - and it doesn't necessarily know the difference between data and instructions."},
    {"vuln_id": "VULN-078", "name": "Insecure Output Handling - XSS via AI Response", "category": "Insecure Output Handling", "severity": "high", "status": "active",
     "hint": "Whatever the AI assistant says back to you gets displayed somehow - think about what happens if its reply contains something that isn't just plain text."},
    {"vuln_id": "VULN-079", "name": "Excessive Agency - Unconfirmed AI-Triggered Financial Writes", "category": "Excessive Agency", "severity": "critical", "status": "active",
     "hint": "The AI assistant can take real actions on your account, not just answer questions - and it doesn't necessarily ask before doing so."},
    {"vuln_id": "VULN-080", "name": "SQL Injection + IDOR - Loan Endpoints", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "Loan data follows the same 'id passed by the client, trusted by the server' pattern as several other features."},
    {"vuln_id": "VULN-081", "name": "Business Logic - No Balance Reconciliation on Transaction Update/Delete", "category": "Insecure Design", "severity": "medium", "status": "active",
     "hint": "Editing or deleting a transaction updates the transaction record - check whether it also updates the account balance that transaction affected."},
    {"vuln_id": "VULN-082", "name": "SQL Injection + IDOR - Scoreboard Progress", "category": "Injection", "severity": "critical", "status": "active",
     "hint": "This very page has to save your progress somewhere - check whether it actually confirms the progress it's saving belongs to you."},
    {"vuln_id": "VULN-083", "name": "Weak Password Reset Token + User Enumeration", "category": "Authentication", "severity": "high", "status": "active",
     "hint": "The password reset flow tells you more than it should about whether an email is registered, and the token it hands out afterward might be easier to guess than you'd expect."},
    {"vuln_id": "VULN-084", "name": "No Rate Limiting - 2FA Code Verification", "category": "Auth Failures", "severity": "medium", "status": "active",
     "hint": "Once you're past the password, the second factor doesn't seem to mind how many times you get it wrong."},
    {"vuln_id": "VULN-085", "name": "SQL Injection + IDOR - Account Reorder", "category": "Broken Access Control", "severity": "high", "status": "active",
     "hint": "Reordering your own accounts sends the server a list of ids - check whether it actually verifies any of them belong to you."},
    {"vuln_id": "VULN-086", "name": "SQL Injection + IDOR - Dashboard Stat Card Order", "category": "Broken Access Control", "severity": "medium", "status": "active",
     "hint": "Saving your dashboard's card layout has to say whose layout it is somehow - see what happens if you say it's someone else's."},
]
