{{- if .Values.vulnerable.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.vulnerable.namespace }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
    aura/version: vulnerable
{{- end }}
